version: '3.8'

services:
  admin:
    build:
      context: ./DarkGate/admin
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./DarkGate/admin/admin.log:/app/admin.log # монтируем volume для логов
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - proxy
    networks: # Добавляем секцию networks
      - darkgate_network

  proxy:
    build:
      context: ./DarkGate/proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./data:/data
      - ./certs:/certs
    networks:  # Добавляем секцию networks
      - darkgate_network

networks: # Объявляем сеть
    darkgate_network:
        driver: bridge