version: '3.8'

services:
  admin:
    build:
      context: ./DarkGate/admin
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./certs:/certs
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

  proxy:
    build:
      context: ./DarkGate/proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
      - "8899:8899"
    volumes:
      - ./data:/data
      - ./certs:/certs
