# docker-compose.yml
version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: ./DarkGate/proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - certs:/certs
    depends_on:
      - admin
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: ./DarkGate/admin/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - data:/data
      - certs:/certs
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  data:
  certs: