# docker-compose.yml
version: "3.8"

services:
  admin:
    build: ./DarkGate/admin
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./certs:/certs
    environment:
      - ADMIN_PASSWORD=your_admin_password
      - SECRET_KEY=your_secret_key

  proxy:
    build: ./DarkGate/proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./data:/data
      - ./certs:/certs
