version: '3.8'

services:
  admin:  #  Меняем на darkgate-admin
    build:
      context: .
      dockerfile: admin/Dockerfile
    image: rfailesdev/darkgate-admin:latest  #  Добавляем явное имя образа!
    ports:
      - "5000:5000"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - SECRET_KEY=${SECRET_KEY:-your_secret_key}
    volumes:
      - dynamic-proxy-data:/data
      - dynamic-proxy-certs:/certs
    networks:
      - darkgate-proxy-network
    depends_on:
      - proxy

  proxy:  # Меняем на darkgate-proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    image: rfailesdev/darkgate-proxy:latest    # Добавляем явное имя образа!
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - dynamic-proxy-data:/data
      - dynamic-proxy-certs:/certs
    networks:
      - darkgate-proxy-network

volumes:
  dynamic-proxy-data:
  dynamic-proxy-certs:

networks:
  darkgate-proxy-network: