version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: ./DarkGate/admin/Dockerfile
    image: dynamic-proxy-admin
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./DarkGate/admin:/app/admin
      - ./DarkGate/common:/app/common
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - proxy
    networks:
      - proxy-network
    restart: always

  proxy:
    build:
      context: .
      dockerfile: ./DarkGate/proxy/Dockerfile
    image: dynamic-proxy-server
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./data:/data
      - ./certs:/certs
      - ./DarkGate/proxy:/app/proxy
      - ./DarkGate/common:/app/common

    networks:
      - proxy-network
    restart: always

networks:
  proxy-network:
    driver: bridge