version: '3.8'

services:
  admin:
    build:
      context: ./dg_app/admin  #  Изменили путь
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./data:/data
      - ./certs:/certs
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - darkgate-network
    depends_on:
      - proxy
    restart: always

  proxy:
    build:
      context: ./dg_app/proxy  # Изменили путь
      dockerfile: Dockerfile
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./data:/data
      - ./certs:/certs
    networks:
      - darkgate-network
    restart: always

networks:
  darkgate-network:
    driver: bridge