# docker-compose.yml (без test_server)
version: '3.8'

services:
  admin:
    build: ./DarkGate/admin
    ports:
      - "5000:5000"
    volumes:
      - ./DarkGate:/app
      - ./data:/data
      - ./certs:/certs
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - proxy
    restart: unless-stopped

  proxy:
    build: ./DarkGate/proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./DarkGate:/app
      - ./data:/data
      - ./certs:/certs
    restart: unless-stopped

volumes:
    data:
    certs: