version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: DarkGate/proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/rules.db:/data/rules.db:rw
      - ./certs:/certs:rw
    networks:
      - darkgate_network
    depends_on:
      - admin  # Важно, чтобы админка запускалась первой (для создания БД)

  admin:
    build:
      context: .
      dockerfile: DarkGate/admin/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data/admin.db:/data/admin.db:rw  # База данных админки
      - ./data/rules.db:/data/rules.db:rw  # Общая база данных правил (для прокси)
      - ./certs:/certs:rw  # Общая папка с сертификатами
      - ./admin_logs:/app/admin.log
    networks:
      - darkgate_network

networks:
  darkgate_network:
    driver: bridge